const YELLOW_WARUNG = "#FECF28";
const YELLOW_DARK_CONTRAST = "#b1901c";
const DARK_SLATE_GRAY = "#1D2F2F";
const SLATE_GRAY_CONTRAST = "#445a6f"

export { YELLOW_WARUNG, DARK_SLATE_GRAY, YELLOW_DARK_CONTRAST, SLATE_GRAY_CONTRAST };
